### ISSUE TITLE
JPEG EXIF orientation

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#1]
JPEG attachments are shown without respecting the EXIF orientation header (i.e. rotated).

In theory, this should be possible via CSS3 [`image-orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation) but sadly it's not yet supported in any browser but Firefox, and it seems to be on its way out of the standard.

Chrome seems to be leaning toward making this default behavior, though.  See https://bugs.chromium.org/p/chromium/issues/detail?id=158753

Likely this will wait for image previews to be done, and we can fix it then.

**Comment by jbosboom** [comment]
Does Chrome break if we add the attribute?  If Chrome just ignores it, we can at least fix this for Firefox users (i.e., me).

**Comment by edemaine** [comment]
All non-reflecting EXIF Orientations are now supported, thanks to the new rotation support.
