### ISSUE TITLE
E-mail notifications contain both raw and rendered math

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#104]
I just received an e-mail notification containing

> e.g. 1×21 \times 21×2 and 2×12 \times 12×1

I don't know if it's related, but one of the two messages in the e-mail also had

>   * Format: markdown

below the message text in the notification.

**Comment by edemaine** [comment]
This is caused by a switch in LaTeX renderer, from MathJax (which wouldn't do anything in email anyway) to KaTeX (which is trying, but doesn't look pretty without its CSS).  I'm turning it off for email notification.
