### ISSUE TITLE
Public and private responses

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#108]
Superuser can mark a thread (root message) as being **publicly respondable** yes/no (default yes), and **privately respondable** yes/no (default no).  All current messages are in the public yes, private no mode.

Public responses are published as usual.  Private responses are unpublished and remain so -- only superusers can publish/unpublish.

Issue: Is published/unpublished the right mechanism for this?  Should there be a private/public or hidden/visible?

**Comment by jbosboom** [comment]
Can I open a private thread with another user?  (Taiga Forum, which runs the Speed Demos Archive forums, uses this feature in place of private messages.)

We may decide we actually don't want to support this, in which case I'm not sure what private responses are actually for.  Anonymous (and hidden) feedback threads?

**Comment by edemaine** [comment]
Together with #107, yes, you'd be able to open a private response with another user.  This is probably not an ideal mechanism for private messaging, but it's a step in that direction.

The purpose of this issue is for solving **solved** in class: the root (public) message can be the solved problem statement, flagged to only allow private responses, and multiple students can post their own private responses, readable only to course staff (superusers).  Later, course staff (superusers) can choose to make one or more of the private answers public (to give out solutions).

Another purpose is to give a system for public and/or private feedback on lecture videos in flipped classes, or lectures in general.  In this case, both public and private responses are allowed, and instructors can respond to either (though for responses to private messages we should take care that private is the default!).  This is kind of like Piazza.
