### ISSUE TITLE
Group creation interface

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#113]
On the main Coauthor page, global superusers (?) should have a UI to create new groups.  (The only way currently is via `meteor mongo`.)

**Comment by sarahscheffler** [comment]
Did this ever get added, btw?  I just set up a coauthor instance (finally! yay!) and am fine adding groups (relatively rare) via mongo, but I'd like to know if there's a UI way.

**Comment by edemaine** [comment]
Yep! You need to be a global superuser, and click 'Become Superuser'. Then it's at the bottom of the main page.
