### ISSUE TITLE
Upload an ordered file sequence

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#115]
When I click 'Attach' and select multiple files in the resulting Open File dialog, they're uploaded in an arbitrary order, instead of the order they were specified in the dialog (at least using Firefox).  That's fixable with reordering/reparenting, but it would be nice to have a way to upload an ordered sequence of files.

**Comment by edemaine** [comment]
I'm also wondering whether the importers deal with this properly.  Should definitely be fixable.
