### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#14]
I am imagining that each user can define two thresholds (each a time delta such as 10 minutes, 1 hour, 12 hours):
1. **Throttling**: Don't report a change to a message (thread?) until it hasn't changed for this period of time.  In particular, I can imagine that, during a session, we don't really want frequent updates -- but a summary after-the-fact would be useful...
2. **FOMO**: Force a report if there have been unreported changes at least this much time ago, even if it contradicts throttling.  This prevents a "live lock" situation where updates keep happening, so you never get a report.

In addition, I can imagine marking either threads or subtrees as (un)interesting to the user, with a global default for every new thread as a user setting (I guess -- though you're really going to miss out if you don't get notifications...).  I guess there could be an intermediate setting where you're told about the first activity in a thread (the original post), but you don't get told about future updates...  A kind of special "new root message" notification choice.

**Comment by jbosboom** [comment]
Minor changes: SO notifies you when your posts are edited, unless the change is smaller than some number of characters (it's not known exactly how many).  This avoids notifying on typo fixes.

Eager notifications: given the live update functionality, I might want to be notified as soon as someone starts editing (once it's not a minor edit), so I can follow along.  In a live problem session setting, I might opt-in to these eager notifications on one or two problems I'm really interested in so I can go talk to the people working on them.  Less useful for the weekly meeting model.

Newly-published posts should not be subject to the quiescence threshold. Assuming users only click 'publish' when they're done, there's no reason to wait another 10 minutes.

Digest mode (lazy notifications): Some people subscribe to mailing lists in digest mode.  If you know one of them, you might ask if they'd like something like that.  This is less useful if we have a good 'show unread' story to catch up with.

FOMO: I hope you can explain that better in the UI; I had to look up what FOMO stands for and it's still not clear how that relates.  How about linking the thresholds as "Notify after quiescent for [10 minutes] but don't wait more than [1 hour]"?

Throttles: If I set a low threshold like 10 minutes, I might get a lot of updates.  I understand 'throttle' to mean something like 'not more than X notifications in Y time'.  This can wait until we actually find it's a problem.

I like the new problem notification.  I have OSQA set to auto-subscribe me to everything, then manually unsubscribe from things I don't care about (though traffic is so low on ours I often don't), but opting-in will work better in larger groups with more problems.  (Also, if you're going to call a setting FOMO, it would be this one.)

**Comment by edemaine** [comment]
Discussing this with Jayson and Adam, here is a more precise proposal:

Each problem (eventually, maybe by subthread) can have one of four levels of "interest" (and there is a default autosubscribe for new messages):
  1. **No** email notification (don't care)
  2. **Batched** email notification: every *b* hours/days, if there have been any changes, tell me about all changes since the last batched update.
  3. **Settled** email notification: if a message has changed and then hasn't changed for at least *s* minutes/hours/days, then tell me about the change.  Perhaps, there is also a maximum out-of-date time *m*, so if things still haven't settled by *m* minutes/hours/days, then tell me that changes are happening.
  4. **Instant** email notification: as soon as someone starts editing a message, send me this type of message.  This allows you to join in the fun.  This mode works in tandem with settled notifications, so that you also learn when it hasn't changed for a while and is worth reading (if you didn't join in live).

So there are only 2 or 3 parameters per user, and four settings per problem, so relatively clean/simple.  

This approach doesn't allow e.g. different settled settings for different problems, or different batched settings for different problems.  I could imagine users being able to create their own levels of interest, with different settings for each, and choosing among them, but would this be worthwhile?  I think mostly people want to have some problems batched, and others settled or instant...

**Comment by edemaine** [comment]
The notification system would also be a good way to add the "show me a stream of all the updates live" in a live problem session.

**Comment by edemaine** [comment]
I've implemented basic email notification of the 'settled' type, with hard-coded 10-minute settling or 60-minute maximum.  Currently users can just toggle it on or off, default is on.

**Comment by edemaine** [comment]
Currently, if someone makes a message and then deletes it, everyone still gets notified (even if they can't read it).  This is because it was readable when it was created...

Also, when sending out notifications, we should send out all active (unseen) notifications for that user -- I think no reason to wait...

**Comment by edemaine** [comment]
I think the notification timers would make more sense at the thread level (problem instead of message within the thread).

**Comment by edemaine** [comment]
Should add a per-user email notification toggle.

**Comment by edemaine** [comment]
I made a big change here.  We're now closer to a batched model, but instead of being at fixed times, we wait an hour after a new post in a quiet period.  Then an hour later, we'll post updates on everything that happened in the meantime.  In slow periods, this will just be the one message, not too late.  In fast periods, this will bunch together a lot of updates.  Updates are scheduled by-user now instead of by-message (as before) or by-group.  Multiple groups and threads are separated out but still in the same message.

**Comment by edemaine** [comment]
I added a user-configurable choice of how many minutes/hours of delay before an update triggers a notification.
