### ISSUE TITLE
Avoid accidental deletions

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#159]
1. Deletion should perhaps have a confirmation dialog, to avoid accidental deletions
2. Should we allow deletions of other people's messages?  Maybe not, except for superuser.

**Comment by jbosboom** [comment]
I don't see why accidental deletions are a problem, because the post can immediately be undeleted.  Undeletion seems to work for other user's messages too, at least in the test group, though maybe I can only undelete because I was the user who deleted?

**Comment by jbosboom** [comment]
Regarding deleting other user's messages, what happens if you reply to my message and I delete my message?  Is your reply reparented, or hidden (effectively deleted)?

**Comment by edemaine** [comment]
Accidental deletions have been a problem lately because people have deleted messages and not noticed that they deleted them. (Also, deleting and undeleting currently causes an email notification, and authorship addition.) In the deleted state, only "authors" (people who have changed the message) can see the message. So only the original author and the deletor can undelete. This is pretty annoying when the deletor didn't notice they did anything, as it removes access from most users. Unless we change who can see deleted messages... 

If you delete a parent, others will no longer see the parent, and children will become orphaned, and displayed at the bottom. I haven't tested this extensively but I think it works (and hopefully reparenting also works).

**Comment by edemaine** [comment]
Hiding within a dropdown menu, as in #172, should hopefully be enough (instead of confirmation dialog).  Closing this with #172 as replacement.
