### ISSUE TITLE
@mentions not allowing private post viewing

### ISSUE THREAD

**Issue by Angrivarius** [edemaine/coauthor#160]
(Reported by Jonathan Tidor.)

**Comment by Angrivarius** [comment]
Specifically, Jonathan Tidor can't see https://coauthor.csail.mit.edu/6.849-2017/m/fRWtBEPwagwgaFYLJ and isn't subscribed to notifications about its parent thread.

**Comment by Angrivarius** [comment]
Same problem at https://coauthor.csail.mit.edu/6.849-2017/m/yYfciyXY9j4t2AWgi .

**Comment by edemaine** [comment]
Also, regarding the "subscription" (which hasn't changed):
* Jonathan Tidor has notifications turned off.
* Evan Chen is not subscribed to that thread (and has default subscriptions turned off).
