### ISSUE TITLE
Hide e-mail in author view, at least for publicly-accessible groups

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#161]
Currently the author view displays the user's e-mail address.  That's probably okay for private groups, but I think it should be hidden from public groups, including the test group.

I don't know what to do about users whose username is their e-mail address.  Someone did try to ask for help changing their username [in the test group](https://coauthor.csail.mit.edu/test/m/kQJQzY5hYPzixZeBw).

**Comment by edemaine** [comment]
The public group 'test' (currently) has no explicit members, so you won't be able to see any information (e.g. email) about the users that post there (unless you happen to have some of that information cached from another group). 

Anyway I think I should delete the test group from the public server. Thoughts? 

Also I think I should forbid @ and spaces in usernames, and try to move existing accounts with those to alternatives. Agreed? I think the email addresses as usernames is the result of browser autofill, not by choice.

**Comment by jbosboom** [comment]
Okay.

Well, there should be a test group around somewhere for testing, but I agree it doesn't have to be public.

Yes, regularize the usernames.

**Comment by edemaine** [comment]
Replaced by #164 and #165.
