### ISSUE TITLE
Email notification subject

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#173]
A special case that'd be nice to improve the email notification subject: all updates are by the exact same set of people.  Then (like the one-update case) we could list that set of people in the subject.  (Or maybe should just handle 1 person, so subject is short...)  Main use case I have in mind is getting an email about my own 4 posts; I'd like to see my name in the subject so I don't need to worry about reading it.

**Comment by jbosboom** [comment]
If that's your use case, maybe just turn off notifications about your own posts?

**Comment by edemaine** [comment]
I like getting them, for some reason.  Partly to make sure email notifications are still working, partly as an absolute fallback if daily backups go haywire, and partly to know when people get them (assuming 1-hour notification timing, which is now actually configurable, but I imagine people will only go up, not down).
