### ISSUE TITLE
Front page should separate between groups user is member of

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#176]
Global superusers (me) can see all groups, but are members of only some.  Would be nice to separate them.  Something like:

```html
<h3>Your Groups</h3>
...
<i>n groups</i>
<h3>Other Groups</h3>
...
<i>m groups</i>
```

Also, once #79 exists, it'd be nice to separate groups in which you are a member from groups you have access to specific messages.

A potentially nicer way to do this is to use tables, like the group view.  Initial columns would be Group Name and Status (member, guest, super).  Then you could sort by desired feature.

**Comment by aureooms** [comment]
What about only displaying all groups in superuser mode (with additional membership information if necessary)? Same question for restricting permissions in non-superuser mode.
