### ISSUE TITLE
Group meta-information thread

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#194]
In addition to threads, groups often have some associated meta-information, such as links to version control repositories.  Each group should have a meta-information thread in a distinguished place in the UI (i.e., not buried down the page) where this information can be posted.

**Comment by edemaine** [comment]
Maybe we could add the notion of "pinning" a thread to make it (always? default?) sort to the top?  Related to #244 (manual problem ordering), #321 (hierarchy of threads).

**Comment by edemaine** [comment]
Partially solved by new tags with values which enables categories and meta categories. Remainder moved to #599.
