### ISSUE TITLE
More detailed installation tips for linux

### ISSUE THREAD

**Issue by aureooms** [edemaine/coauthor#199]
On linux, the meteor installation script needs tar and gzip. Add line in installation steps about this.

**Comment by aureooms** [comment]
Also `git clone` needs git and `meteor npm install` needs python.

**Comment by aureooms** [comment]
python2 to be precise and also make.

**Comment by aureooms** [comment]
and g++/gcc and sed

**Comment by aureooms** [comment]
`meteor mongo` needs ps

**Comment by aureooms** [comment]
Also, a weird error can happen for people using MongoDB for the first time on a fresh linux install: [MongoDB needs /etc/default/locale to be filled with stuff](https://github.com/meteor/meteor/issues/4019). Failing to do so will result in the cryptic error

    Unexpected mongo exit code 1. Restarting.
    Unexpected mongo exit code 1. Restarting.
    Unexpected mongo exit code 1. Restarting.
    Can't start Mongo server.

Tell me if I can just edit the README and send you a pull request with all those changes.

**Comment by edemaine** [comment]
Are there UNIX systems without `tar`, `gzip`, `sed`, and `ps`?  I thought these were part of the base install on all known UNIXes, but I guess not.  Which one?  (For example, with a base Ubuntu install, I didn't have to add anything.)

**Comment by aureooms** [comment]
Arch Linux

**Comment by edemaine** [comment]
https://www.archlinux.org/groups/i686/base/ ?

**Comment by aureooms** [comment]
I agree this is not a common Linux issue. The information could be in the README in a one-liner that says: "Make sure to have tar, gzip, git, python (version 2.x), make, g++, sed and ps installed, as well as your /etc/default/locale properly configured."

**Comment by aureooms** [comment]
Ok maybe, this is because I used the base/archlinux docker container.

**Comment by aureooms** [comment]
Ok, [the base group should be installed](https://bugs.archlinux.org/task/53919#comment157443).

**Comment by aureooms** [comment]
The base group does NOT contain git, python2, make, gcc.

**Comment by jbosboom** [comment]
gcc and make are in [base-devel](https://www.archlinux.org/groups/x86_64/base-devel/); git and python2 are in their eponymous packages.  In general, run `pacman -Fy` to download the files database, then `pacman -Fs <command>` to see which packages own files with that name.

**Comment by aureooms** [comment]
@jbosboom What is the difference with `pacman -Qo` which I used?

**Comment by aureooms** [comment]
The `backup.sh` script needs `mongodump` which is found in `mongodb-tools` on Arch (optional dependency of `mongodb` so not automatically installed).

**Comment by edemaine** [comment]
Added documentation about this to `backup.sh` script.  I don't think it's useful to document here how to install Meteor, as that's a Meteor issue, not specific to Coauthor.
