### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by aureooms** [edemaine/coauthor#202]
I installed postfix, configured it as described in the README and started it. However the server is not able to send emails.

    ====== BEGIN MAIL #1 ======
    (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
    ...

What is this environment variable for and what should it contain?

**Comment by edemaine** [comment]
https://docs.meteor.com/api/email.html

**Comment by aureooms** [comment]
Not using mup for the moment but might in the future to avoid the hastle.
