### ISSUE TITLE
Kadira open-source server

### ISSUE THREAD

**Issue by aureooms** [edemaine/coauthor#204]
[End of transmission](https://kadira.io/). Any replacement for that?

**Comment by edemaine** [comment]
Now we need to [run our own server](https://github.com/kadira-open/kadira-server).  I haven't tried it yet, but eventually plan to.

**Comment by edemaine** [comment]
README has been updated, but should still test the open-source Kadira server.

**Comment by edemaine** [comment]
I got this working for me, on a separate server from the main Coauthor server, using `docker-compose`.  See https://github.com/edemaine/kadira-compose (also linked to from Coauthor's INSTALL.md).
