### ISSUE TITLE
nginx + force-ssl incompatibility

### ISSUE THREAD

**Issue by aureooms** [edemaine/coauthor#205]
If one uses nginx to proxy a locally running docker container which only serves http then [force-ssl should be disabled as explained here](https://stackoverflow.com/a/26939568/1582182). I am using this setup so I had to run `meteor remove force-ssl` for it to work properly.

This is just a note and I think it should be added to the README because the way to figure this out is a bit tricky. If you do not remove force-ssl the symptom you get is an infinite 302 redirection from the proxied address `http://locahost:3000` to `https://coauthor.foo.bar.baz`.

**Comment by edemaine** [comment]
To be clear, are you still using `mup` in this setup?  Trying to figure out which section of the README to mention this.

**Comment by aureooms** [comment]
Here is the fork https://github.com/aureooms/coauthor
