### ISSUE TITLE
Source email address hardcoded

### ISSUE THREAD

**Issue by aureooms** [edemaine/coauthor#206]
Currently non-softly configurable and present two times in https://github.com/edemaine/coauthor/blob/987cf66e319a2d0eb79fab198b191b1947a23b57/server/email.coffee#L5

**Comment by edemaine** [comment]
I'd suggest that this hostname should come automatically from the `ROOT_URL` environment variable (as set in `.deploy/mup.js`).  (Of course, it could still be manually overridden by editing `server/email.coffee`.  I assume this would work in your case?

**Comment by aureooms** [comment]
I would still have to edit `server/email.coffee` because I am using `coauthor@ulb.ac.be` and `ROOT_URL` is `coauthor.ulb.ac.be`.

**Comment by edemaine** [comment]
There's now no hard coding; the default is to use `coauthor@` the server's hostname; but you can override via the `MAIL_FROM` environment variable.  Let me know whether it works for you.
