### ISSUE TITLE
User subscribed to notifications of unpublished post, despite not being @-mentioned

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#209]
Jayson is shown as subscribed to https://coauthor.csail.mit.edu/6.890/m/yW2rEE23QEZjsdLEL (unpublished) despite not being @-mentioned in the post.  I did write "Jayson said" in the post, but I didn't expect that to subscribe him.  (This autosubscription seems especially problematic in groups in which multiple people have the same name.)

There doesn't seem to be any way to un-subscribe him.  I edited the post to say "Jay son said" (breaking up his name) but he's still shown as subscribed, even after refreshing the page.

**Comment by edemaine** [comment]
This was just because Jayson was a superuser member of the group.  Naming him was a red herring.
