### ISSUE TITLE
E-mail notification time zones

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#210]
While times in Coauthor itself are displayed in (presumably) the browser's timezone, e-mail notifications contain timestamps that are always in UTC.  This feature request asks for a setting to specify a user's time zone so notifications can use it.

**Comment by edemaine** [comment]
Agreed. I'd even thought of it before (#143) -- I agree that a setting in Settings would be a good way to go.

**Comment by edemaine** [comment]
This was harder than I expected. There are a lot of timezones out there! So building a UI for selecting them was annoying. I tried a hierarchy of menus to select from the IANA list, but it's not exactly intuitive. Instead I settled on an autocompleting/suggesting text field with substring search, with the IANA list augmented with country names. This seems to work pretty well.
