### ISSUE TITLE
side-by-side editor

### ISSUE THREAD

**Issue by calischs** [edemaine/coauthor#211]
Erik and I talked about a few potential enhancements which would be useful in editing long posts. 
 One was a side-by-side editor, where source and rendered content are displayed in two scrollable columns.  This would save lots of scrolling.  Note, we can already imitate this behavior by opening two browser windows.

**Comment by edemaine** [comment]
There's now a Side-by-Side vs. Top-Bottom button at the bottom of the editor, and a default under Settings.  Currently the editor remains fixed height, and preview is whatever height it needs (so no scrolling).  Let me know if you have any comments!

**Comment by calischs** [comment]
Thanks for the feature!

As a comment, I would actually prefer they both be fixed height with scrolling.  My use case is working on a long-ish post, and I want to see my updates as I type them (without scrolling).  As it is now, if I'm working on content at the end of the post, I still have to scroll down from the editor to see the changes.

**Comment by edemaine** [comment]
I wondered that. I'll give it a try. (Or of you get a chance to play with the CSS, feel free!)

**Comment by edemaine** [comment]
OK, I tweaked the CSS to set the preview to the same height (300px) in side-by-side mode.  Ideally this height would be draggable and/or configurable, but that's for another issue...

**Comment by calischs** [comment]
Looks great!

**Comment by edemaine** [comment]
Great!!
