### ISSUE TITLE
ability to toggle rendering for quickly writing source content

### ISSUE THREAD

**Issue by calischs** [edemaine/coauthor#213]
I'd love the ability to turn off rendering temporarily during editing so I can jot down source quickly without the lag introduced by rendering.

**Comment by edemaine** [comment]
We could definitely turn off previews for the specific message that you're editing, as another option like side-by-side (#211).

**Comment by jbosboom** [comment]
My 6W laptop processor would really appreciate this.

**Comment by edemaine** [comment]
There's now a "Disable Preview" button (and a default under Settings).  Let me know if you have any comments!

**Comment by jbosboom** [comment]
Disabling the preview doesn't fix the editor lag I'm experiencing.  If we ever have dev meetings again we can try out the Firefox profiler to see what's up.

**Comment by edemaine** [comment]
@calischs Can you let me know if disabling previews help your rendering speed at all?

**Comment by calischs** [comment]
Unfortunately, I'm still experiencing editor lag as well.

**Comment by edemaine** [comment]
I've pushed a fix to #219 which should fix this issue.  Let me know if things work better.

**Comment by calischs** [comment]
Nice!  Editor is very responsive now, even without disabling preview.  If I try very hard, I can get a typing delay while editing a long post.  ;)

**Comment by edemaine** [comment]
Sweet!  I'm going to declare this done.
