### ISSUE TITLE
History does not display content

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#215]
History no longer displays content, just the slider.  Related to #213 changes?

I discovered this trying to view the history of a post I'd disabled the preview on while editing, but even after turning it back on, no history content is rendered.  Posts I've never edited also don't show history, and refreshing the page does not fix it.

**Comment by edemaine** [comment]
Oops, indeed, I broke it.  Pushing a fix now.

**Comment by edemaine** [comment]
(finally pushed -- history seems to work again)
