### ISSUE TITLE
Diffs in thread update emails

### ISSUE THREAD

**Issue by bdsullivan** [edemaine/coauthor#221]
It would be (extremely) helpful to be able to quickly identify *what* changes were made when a thread is updated. As it is, it's hard to tell whether an update is fixing a typo or making substantive content changes. 

Could the automated emails include a diff? Or highlight the new/changed text in some way? 

Thanks!

**Comment by edemaine** [comment]
Indeed, this is issue #89.  There are technical reasons why this is tricky to do, but of course it can and should be done.
