### ISSUE TITLE
Send one e-mail per group when sending e-mail notifications

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#237]
I'd like e-mail notifications kept separated by group so that I may have them delivered into separate folders using e-mail filters.

I imagine some users would like to receive combined e-mails, and Coauthor itself probably prefers to send as few e-mails as possible, so this should be behind an option.  (Also, maybe you can improve the performance of notification scheduling while you're working on that code.)

**Comment by edemaine** [comment]
I've wondered about/desired this too.  Sounds like a good option to add.

Presumably each group should be independently timed (so you get email an hour after the first modification in each group).  I think this can be done... after a user's timer activates and we process one group, I'll need to figure out when to set the next timer for the remaining groups.

**Comment by edemaine** [comment]
This is finally deployed.  Check out new "Separate by group" setting.
