### ISSUE TITLE
Coauthor logging out

### ISSUE THREAD

**Issue by jaysonl** [edemaine/coauthor#252]
Coauthor has been logging me out a lot lately. It occurred twice during 6.851 class yesterday and now three times today. Might be my problem (had difficulties with Google News since yesterday), though Adam also mentioned experiencing similar problems. I'm using Chrome on Windows 10.

**Comment by edemaine** [comment]
I've seen this occasionally myself, and heard about it from several others.  Luckily I believe Meteor 1.5.2.2 [fixes](https://github.com/meteor/meteor/pull/9148) the problem.  (Rocket.Chat was reporting the same issue.)  Let me know if you see it again!
