### ISSUE TITLE
Clicking links in the sidebar (the list of all messages in the thread) sends me to the Coauthor home page

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#254]
The sidebar links look like `https://coauthor.csail.mit.edu/#6B6CFmwAwaBugjGEH`, with no group in them, and after clicking I arrive at `https://coauthor.csail.mit.edu/#!?__hash__=6B6CFmwAwaBugjGEH`, which is just the Coauthor group list home page.

**Comment by edemaine** [comment]
Thanks for spotting this quickly.  Apparently a side effect of the `appcache` package I was experimenting with.  Removed and back to normal.
