### ISSUE TITLE
Actions menu should pop upward to remain in viewport

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#256]
Right now, move the mouse to the bottom of the screen and right-click.  The menu pops upward instead of downward, to remain on the screen.

In Coauthor, if the 'Actions' button is near the bottom of the viewport, clicking it still pops downward, off the viewport.  It should remain in the viewport, if possible.  (Or maybe the viewport should autoscroll to fit it.)

**Comment by edemaine** [comment]
This seems to be [automatic behavior in Bootstrap 4](http://getbootstrap.com/docs/4.0/components/dropdowns/).  I was wondering if there were reasons to upgrade...
