### ISSUE TITLE
Table of contents sidebar

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#26]
Here's a nice way to see the big picture while also seeing the details of a message thread: let's add a table of contents sidebar.  This would have the side benefit of making the main text narrower, which should be easier to read.  Also it would be a good place to do dragging of submessages (#13).
[Jeffrey]

**Comment by edemaine** [comment]
I'm not a big fan of how the top nav disappears but still takes up space in the table-of-contents sidebar... but it's a good start!

**Comment by jbosboom** [comment]
It'd be nice to collapse (and expand) messages from the sidebar, as with directory tree views in many file managers.
