### ISSUE TITLE
Attaching to someone else's unpublished post doesn't work

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#260]
I tried three times to attach a file to https://coauthor.csail.mit.edu/6.871-fall2017/m/HcLSoLcgjqkJ3LYM4 , but none of them worked (or at least, I don't see any of the created messages).  The console shows `Error uploading b4205b3b2040ffb0dd95d484` and a backtrace inside `files.coffee.js/<` at `  2e1e6a951573d5abc43134f7543c8d3f3f7c2b8b.js:209:325241`.

I don't actually know if being someone else's unpublished post is related or not.  I tried both without and with "becoming superuser" via the button in the top bar, and again with a shorter filename (in case that was related).

**Comment by edemaine** [comment]
I'm guessing I broke attaching in general. I'll be able to work on this in about 30 minutes. Meanwhile, feel free to look at the Network tab to see what's actually going wrong.

**Comment by edemaine** [comment]
Hmm, I'm unable to reproduce.  Perhaps you were trying this at the exact moment I was restarting the server today (4pm &pm; 10 minutes)?  I successfully attached a file to that message, and some others.

If you still see a problem, it must be specific to users or permissions...  Please let me know.

**Comment by jbosboom** [comment]
Still not working.  I see two HEAD requests to `https://coauthor.csail.mit.edu/gridfs/fs/_resumable?resumableChunkNumber=1&resumableChunkSize=2096128&resumableCurrentChunkSize=2096128&resumableTotalSize=6103111&resumableType=application%2Fpdf&resumableIdentifier=586c391c4b7b14518615b7d0&resumableFilename=Multi-core%20parallelism%20for%20plane%20sweep%20algorithms%20as%20a%20foundation%20for%20GIS%20operations%20(McKenney%2C%20Frye%2C%20Dellamano%2C%20Anderson%2C%20Harris%2C%202016).pdf&resumableRelativePath=Multi-core%20parallelism%20for%20plane%20sweep%20algorithms%20as%20a%20foundation%20for%20GIS%20operations%20(McKenney%2C%20Frye%2C%20Dellamano%2C%20Anderson%2C%20Harris%2C%202016).pdf&resumableTotalChunks=2` which get 204 No Content, then POST requests to `https://coauthor.csail.mit.edu/gridfs/fs/_resumable?resumableChunkNumber=1&resumableChunkSize=2096128&resumableCurrentChunkSize=2096128&resumableTotalSize=6103111&resumableType=application%2Fpdf&resumableIdentifier=586c391c4b7b14518615b7d0&resumableFilename=Multi-core%20parallelism%20for%20plane%20sweep%20algorithms%20as%20a%20foundation%20for%20GIS%20operations%20(McKenney%2C%20Frye%2C%20Dellamano%2C%20Anderson%2C%20Harris%2C%202016).pdf&resumableRelativePath=Multi-core%20parallelism%20for%20plane%20sweep%20algorithms%20as%20a%20foundation%20for%20GIS%20operations%20(McKenney%2C%20Frye%2C%20Dellamano%2C%20Anderson%2C%20Harris%2C%202016).pdf&resumableTotalChunks=2` and `resumableChunkNumber=2
resumableChunkSize=2096128
resumableCurrentChunkSize=4006983
resumableTotalSize=6103111
resumableType=application%2Fpdf
resumableIdentifier=586c391c4b7b14518615b7d0
resumableFilename=Multi-core%20parallelism%20for%20plane%20sweep%20algorithms%20as%20a%20foundation%20for%20GIS%20operations%20(McKenney%2C%20Frye%2C%20Dellamano%2C%20Anderson%2C%20Harris%2C%202016).pdf
resumableRelativePath=Multi-core%20parallelism%20for%20plane%20sweep%20algorithms%20as%20a%20foundation%20for%20GIS%20operations%20(McKenney%2C%20Frye%2C%20Dellamano%2C%20Anderson%2C%20Harris%2C%202016).pdf
resumableTotalChunks=2` which get 403 Forbidden.  These requests are very rapidly retried five times each (still alternating) plus one more try of the first one, for 11 total failed requests.

**Comment by edemaine** [comment]
Can you confirm that the Forbidden access is not sending a cookie? (specifically X-Auth-Token) Are the other addresses sending such a cookie? (Don't paste the cookie.) Can you try executing the following in the console?

```javascript
$.cookie('X-Auth-Token', Accounts._storedLoginToken(), {path: '/'}) 
```

**Comment by jbosboom** [comment]
The forbidden requests _do_ include `X-Auth-Token` (and no other cookies), and it's the same value as running the command you gave (without the `path=/` part).

**Comment by jbosboom** [comment]
I am seeing the same errors trying to attach to `https://coauthor.csail.mit.edu/6.890/m/yW2rEE23QEZjsdLEL`, which is an unpublished post I authored.

**Comment by edemaine** [comment]
OK, at least it's not a cookie problem. I pushed a change that might help. Can you reload and try again, ideally on laptop?

**Comment by jbosboom** [comment]
Still failing, from both computers.

**Comment by edemaine** [comment]
I'm still suspicious of some code I changed today, so I've rolled back most of today's changes. Could you try one more time?

**Comment by jbosboom** [comment]
It works now.  So, at least you have a range to bisect through...

**Comment by edemaine** [comment]
Yay! Hopefully I can find a way to reproduce the problem myself, probably with another user. Otherwise we might need to sit down together at some point.

**Comment by edemaine** [comment]
All fixed.
