### ISSUE TITLE
Move reply/attach buttons of file messages into actions dropdown

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#268]
When uploading a sequence of images, it's very tempting to hit the attach button that appears on the previous image, but doing so adds the new image as a child of the previous, which is generally not what I want.  Most cases in which we replied to file messages were to add comments/captions, which are now covered by editing the file message's body text.  In general, replying and attaching to file messages does not seem very useful.

I propose moving those buttons into the file message's actions dropdown, so they're still accessible if that really is what you want to do, but they stop being an attractive nuisance.

**Comment by edemaine** [comment]
Closing this barring better ideas. In practice, we now see lots of long file messages, so replies to them are fairly common. To attach multiple files, you can always drag multiple files onto the Reply/Attach button.
