### ISSUE TITLE
"ReferenceError: ShareJS is not defined" after meteor update

### ISSUE THREAD

**Issue by gedetil** [edemaine/coauthor#277]
After a meteor update, coauthor dies with the following error:

W20180110-09:54:00.389(-6)? (STDERR) /data/coauthor/.meteor/packages/meteor-tool/.1.6.0_1.1aeq76u.qepo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180110-09:54:00.390(-6)? (STDERR)                                           throw(ex);
W20180110-09:54:00.390(-6)? (STDERR)                                           ^
W20180110-09:54:00.390(-6)? (STDERR) 
W20180110-09:54:00.390(-6)? (STDERR) ReferenceError: ShareJS is not defined
W20180110-09:54:00.391(-6)? (STDERR)     at sharejs-server.js (packages/mizzao:sharejs/sharejs-server.js:8:24)
W20180110-09:54:00.391(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180110-09:54:00.391(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180110-09:54:00.391(-6)? (STDERR)     at /data/coauthor/coauthor/.meteor/local/build/programs/server/packages/mizzao_sharejs.js:126:15
W20180110-09:54:00.391(-6)? (STDERR)     at /data/coauthor/coauthor/.meteor/local/build/programs/server/packages/mizzao_sharejs.js:132:3
W20180110-09:54:00.392(-6)? (STDERR)     at infos.forEach.info (/data/coauthor/coauthor/.meteor/local/build/programs/server/boot.js:414:13)
W20180110-09:54:00.392(-6)? (STDERR)     at Array.forEach (<anonymous>)
W20180110-09:54:00.392(-6)? (STDERR)     at /data/coauthor/coauthor/.meteor/local/build/programs/server/boot.js:413:9
W20180110-09:54:00.392(-6)? (STDERR)     at /data/coauthor/coauthor/.meteor/local/build/programs/server/boot.js:463:5
W20180110-09:54:00.392(-6)? (STDERR)     at Function.run (/data/coauthor/coauthor/.meteor/local/build/programs/server/profile.js:510:12)
=> Exited with code: 1 
=> Your application is crashing. Waiting for file change.

Any idea how to fix this?  I need to get coauthor running again, as we have documents that we can't access until I do.

**Comment by edemaine** [comment]
Master branch does not have this problem; it was fixed a while ago. Be sure to get commits that transition from mizzao:sharejs to edemaine:sharejs.

**Comment by gedetil** [comment]
OK.  I'm a total noob at this, and just followed the INSTALL.md instructions initially.  What's the easiest way to get my old copy of coauthor updated to the most current stable branch, without losing any of my stored data?  (I.e. I don't want to just reinstall.)

**Comment by edemaine** [comment]
Try `git pull`. Then `mup deploy` assuming you're using mup.

**Comment by gedetil** [comment]
Thanks.  Doing "git pull" complained about discrepancies, which it suggested I should either merge or stash.  Merging didn't seem like a good idea to me, so I did a "git stash", which I hope was the right call.

I don't have mup, but doing "meteor npm install" (as per INSTALL.md) seemed to do the trick.

I'm logged in now, and the Users list seems complete, so I'll assume everything is fine now.

**Comment by edemaine** [comment]
Glad it's working!  I take it you're running the server with just `meteor`.

The conflicts were likely caused by running `meteor update` yourself. In general, you probably don't want to do that, and should instead just `git pull` (which will include updating Meteor, when Coauthor gets upgraded to newer Meteor).

**Comment by gedetil** [comment]
Yes, I had a shell script that ran the server via the meteor command.  I had set up the script to run automatically (detached from a terminal) when the system rebooted, but that would fail for some reason when meteor would complain about updates being available.  Manually running meteor update would usually fix things, and get the script to work again in the background.

I'll try to avoid updating things if I can, as long as the script continues to work, but if it fails, I'll try the git pull first, before updating anything else.

Thanks again!

**Comment by ashrakat** [comment]
For meteor 1.7 codeMirror 5.22.0 won't work with most of us, i don't know the issue but my guess is not stable yet or compatible with meteor 1.7 so go to .meteor/versions and replace code mirror & shareJs versions with these two lines:
mizzao:sharejs@0.8.0
mizzao:sharejs-codemirror@4.12.1
it worked for me

**Comment by miguelpc94** [comment]
> For meteor 1.7 codeMirror 5.22.0 won't work with most of us, i don't know the issue but my guess is not stable yet or compatible with meteor 1.7 so go to .meteor/versions and replace code mirror & shareJs versions with these two lines:
> mizzao:sharejs@0.8.0
> mizzao:sharejs-codemirror@4.12.1
> it worked for me

Great! It worked for me as well. Thanks!
