### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#28]
We can change "Stop Editing" to "Commit" or "Done" and flag those updates as special committed versions.  Then when viewing history, could see committed versions only by default, and have a toggle to see more granularly. [Jeffrey]

Or even better might be to double click on a Commit edit to expand the smaller edits that created.

**Comment by jbosboom** [comment]
There should be a cancel/reset/revert button here too.  Or better yet, just a bare link, to make rare actions less prominent -- note that editing the title of this GitHub issue displays a Save button and a 'cancel' link.

Not sure what cancelling during collaborative editing should do.

**Comment by edemaine** [comment]
There's a big difference between us and GitHub, which doesn't send changes to the server until you hit "Save".  Cancel is nontrivial for us, because changes are constantly being propagated to server (and other users), which is good for collaboration.  It could be implemented by keeping track of the version number when 'Edit' was pressed, so you know what version to revert to.  Maybe it could just be disabled if some of the changes are made by other users...

**Comment by jbosboom** [comment]
Well, when editing a paper locally, I often start working on a paragraph and then realize I can't actually improve it.  Because we're sending changes to the server eagerly, I'd have to repair my edits.

That said, I don't expect to abandon my in-progress edits that often, so I'd be satisfied with reverting manually from the history view.  The revert button would be disabled if other users have the editor open.

**Comment by edemaine** [comment]
I realize that, once we keep track of which edits are "commits", it'd be easy to set the contents back to the last one when clicking a Cancel button. Probably this should have a confirmation dialog ("ok to replace message with this old version?").

**Comment by edemaine** [comment]
Edits are now marked special when hitting Stop Editing, auto timing out, doing an Action, or adding/replacing file.  There's a History toggle to show all or just finished edits.  Some tweaks might be desirable, but I'm going to call this done, and leave follow-ups for new issues.

(If you think a phrase other than "Stop Editing" is superior, let me know, but I couldn't think of one that was clearly the inverse of "Edit".  Maybe "Finish Editing"?)
