### ISSUE TITLE
Text in PDF not rendered

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#300]
https://coauthor.csail.mit.edu/6.871-fall2017/m/GbC7F3EtPLBoFK3Xf just renders like this in Firefox 59.0.1 on both Windows 7 and Linux:
![bad-pdf](https://user-images.githubusercontent.com/7757340/38059732-9ea0dcb2-32b5-11e8-973f-54f153162fea.png)

That is, only the various horizontal lines (in table headers, etc.) are rendered, not the text.

It renders correctly in Firefox's own PDF pseudo-plugin (also built with PDF.js) and in SumatraPDF.  At least in SumatraPDF it does have OCR'd text that can be selected and copied, but the 'text box' is just at the baseline of the text.

**Comment by edemaine** [comment]
I notice that the console says `Warning: Unimplemented operator dependency` which might be relevant...

Note that Coauthor is using pdf.js's experimental SVG engine, which I'm not sure Firefox uses (yet?), which explains the discrepancy -- but not the bug.

**Comment by edemaine** [comment]
Fixed now that we've switched to Canvas rendering.
