### ISSUE TITLE
Full user list of threads not visible to admins of threads who are not group admins

### ISSUE THREAD

**Issue by slef** [edemaine/coauthor#310]
probable fix: replace `groupRoleCheck` by `messageRoleCheck` in `users.coffee` line 48

**Comment by edemaine** [comment]
The bug wasn't quite that easy to fix, as the subscription is given just the group, not the message, but I got it working in https://github.com/edemaine/coauthor/commit/e7095c658272043b1eb0efc1bae4cc0823247ebd
