### ISSUE TITLE
'Open in new window' icon doesn't open in new window, isn't a link

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#32]
So this button actually doesn't do what I thought it did when I suggested this icon.  Instead of opening in a new tab/window, it 'zooms in' the current window.  This is surprising.  If we want that behavior, we should use a zoom-related icon.

This button should be a link so I can middle-click to open in a new tab, or right-click -> Copy Link Location to copy a URL so I can link to a message from another message (possibly in another topic).  (The latter case may not work -- I can't tell if that hash at the end of the URL is user-specific or not.  If it does not work, open a new issue for user-independent permalinks to messages.)

**Comment by edemaine** [comment]
Message IDs/hashes are user-independent, among users who have read access.  They are indexes into the global Messages database.
