### ISSUE TITLE
Nested enumerate labels

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#328]
Currently
```latex
\begin{enumerate}
\item One
\begin{enumerate}
\item Two
\end{enumerate}
\end{enumerate}
```
renders like

```markdown
1. One
   1. Two
```

We should ideally match LaTeX's default behavior (`(a) Two`).

Related to #258. Ideally we'd also support the `enumerate` package's optional argument for manual labeling.

**Comment by tomhull0** [comment]
Yes — I just noticed this. Is there an easy way to fix this?

**Comment by edemaine** [comment]
I'm working on a fix now. Thanks for the reminder on this issue!

**Comment by edemaine** [comment]
I've added LaTeX-like default behavior.  (I'll update the server later today.)  Still no support for optional arguments to `\begin{enumerate}` or `\item`, though I believe these are possible.  For example, this might do custom item labeling:
```css
li.custom:before { content: attr(data-custom) }
```
