### ISSUE TITLE
Shared whiteboard

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#345]
*This has split off into a separate project, [Cocreate](https://github.com/edemaine/cocreate). Integration issue is now #515.*

Devices with pens (Microsoft Surface Hub, Microsoft Surface, iPad Pro), as well as mice, would like to be able to draw on a shared whiteboard surface, maybe a type of post?  [Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) make high-quality input possible via a purely web interface. Related to e.g. shared spreadsheet (#180) except there isn't a great existing service out there.

Jason would also like synchronized audio recording (when you click a button) and playback.

Perhaps posts have a Draw button. We could imagine the ability to jointly annotate any image/PDF. For nonfile posts, or maybe as a separate post type, you can choose an aspect ratio (portrait, landscape, square) and background (grid of various types) and then start drawing?

#347 pairs nicely with this: maybe Draw is a pen button (along with other drawing options) only in full-screen mode, where you have room.

I'm imagining a separate database for annotations/drawings, where each path/line/rect/circle/etc is a document (and past edits to such are in another diffs database). The server can assign a sequence number to added objects, and clients can re-order if it doesn't match SVG build order, to guarantee consistent stacking across devices.

Desired features:

- [x] Toggling/separation of touch vs. pen input (via [`pointerType` property](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType))
- [ ] Touch to pan, pinch to zoom (when touch drawing is off, or when in scroll/zoom mode)
- [x] Pressure sensitivity during stroke (via [`pressure` property](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pressure))
- [ ] Smooth stroke path after draw (how is this done?)
- [ ] Multiple pen types?
- [ ] Pen angle triggers other mode, e.g., shading pen, maybe selectable
- [ ] Can we detect pen buttons? If so, good for selection
- [x] Undo/redo (of local operations; global option?)
- [x] Laser pointer (can see others' cursors)
- [ ] List of participants, click to see their view
- [x] Multiple pages
- [x] Select past strokes by (shift/ctrl) clicking on one
- [ ] Lasso select
- [x] Move them around
- [x] Change their color and stroke width
- [ ] Scale by dragging bounding box corners
- [x] Delete
- [x] Duplicate (or copy/paste)
- [ ] Group strokes? Maybe not worth it, and hard to represent
- [x] Text (for those on keyboard) 
- [x] Lines, rectangles, circles (for those using mouse)
- [ ] API for custom drawing plug-ins?
- [x] SVG export, including of selection
- [ ] SVG import? 
- [ ] Addition of multiple background images? Or maybe can embed an existing attachment?
- [ ] Pasting images
- [ ] Raise/lower? This is tricky. 

It would also be nice if the whiteboard code is modular so that a whiteboard server could be split off from Coauthor...

**Comment by cben** [comment]
https://softwarerecs.stackexchange.com/questions/11882/real-time-interactive-whiteboard-for-tutoring-math collects some existing services. Unclear if any of these are embeddable.

Some open source ones:
https://github.com/spacedeck/spacedeck-open
https://github.com/ova2/online-whiteboard
https://bigbluebutton.org/

**Comment by edemaine** [comment]
@cben Thanks for the links. Of the open source ones you linked, only http://bigbluebutton.org seems to support drawing freehand with a pen (though I may have missed something). Also some of the closed-source services on the StackExchange list might be worth just embedding, as with Google Sheets.

**Comment by jmftrindade** [comment]
If closed-source services are ok, then https://jamboard.google.com/ may be an option.

**Comment by edemaine** [comment]
This is splitting into its own project, [Cocreate](https://github.com/edemaine/cocreate/), at least for now; integration with/embedding into Coauthor to come later.

**Comment by edemaine** [comment]
Moved integration issue to #515
