### ISSUE TITLE
Bold math

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#360]
I'd like `**$(k+1)$-partite**` and `\textbf{$(k+1)$-partite}` to render the `$(k+1)$` in bold, like `$\bm{(k+1)}$` would. 

Implementation idea: Perhaps when expanding and reinserting the math expressions, we can check whether they're in a bold context, and wrap the TeX in `\bm{...}` if so.  This is trickier with things like `\textbf{\textrm{$k+1$}}`.  

Similarly, we might want **message titles** to have this on by default, as they render in a bold font, so would be less jarring.

**Comment by cben** [comment]
LaTeX doesn't do this, neither in headings nor in textbf:
https://www.overleaf.com/2390992sdswkp

I think the reason is that bold math may be santically different (e.g. vector vs scalar)?

**Comment by edemaine** [comment]
Agreed, LaTeX does not do so by default, but I usually enable it (for section headings) via these macros:
```latex
\let\realbfseries=\bfseries
\def\bfseries{\realbfseries\boldmath}
```

Maybe this feature should be a toggleable setting (related to #341), but I've personally never been in a setting where I didn't want bold to carry into mathematics.  Maybe it's partly because bolding is relatively rare in paper writing.  But I do use bold to indicate vectors sometimes, yet I've never wanted to include something where bold vs. nonbold made a difference inside a bold definition, as that would just be confusing writing.  On the other hand, I can't count the number of times I've used `\boldmath` or similar to force bold math inside `\textbf`.

**Comment by edemaine** [comment]
Remaining issue: autobold math in message titles (which always render bold)
