### ISSUE TITLE
Clicking on TOC should open the post

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#362]
If I click on a TOC link and the post is hidden because it or one of its ancestors is folded, then nothing happens.  Instead, all ancestors should be unfolded so that scrolling can happen.

Related, it might be nice to show the folded state of a message/ancestor in TOC (perhaps a gray background or more muted foreground color?), so that minimized chunks are colored differently / easier to skip over in the TOC.

**Comment by jbosboom** [comment]
Would be particularly handy for navigating this well-organized topic: https://coauthor.csail.mit.edu/6.892-2019/m/AqxW4Faid4YQMGqfg
