### ISSUE TITLE
$ in code blocks shouldn't enter math mode

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#387]
See https://coauthor.csail.mit.edu/6.892-2019/m/kwThr56jLjLKbcevT .  Besides messing up the code, being in math mode causes the parser to miss the end of the fenced code block.

Relatedly, \``\emph{}`\` shouldn't trigger LaTeX expansion, because it's wrapped in `s.

Plan: Extract verbatim-like blocks (via backtick regex in Markdown mode), then run other processing, then put it back.

**Comment by diomidov** [comment]
This bug still exists for [indented code blocks](https://spec.commonmark.org/0.29/#indented-code-block): https://coauthor.csail.mit.edu/coauthor-dev/m/AYHWtcbWj9Zik34kS
