### ISSUE TITLE
weird line justification in itemize

### ISSUE THREAD

**Issue by tomhull0** [edemaine/coauthor#399]
In LaTeX mode, I'm getting weird behavior from the itemize environment.  Text that wraps around the first line of an \item seems to be forced to be right and left justified?  Here's an example:
https://coauthor.csail.mit.edu/MathILy-EST-2019/m/yApXFw2uPLgNYK59f

**Comment by edemaine** [comment]
I'm a little confused what you mean. All text in Coauthor is fully justified (like default LaTeX). What are you seeing in that example that isn't as you expect? Also, which browser are you using? (Maybe what you're seeing is different from what I'm seeing.)

**Comment by tomhull0** [comment]
Hi Erik!

Here's a screen shot from Chrome.  But this also happens in Safari.

--- Tom

[cid:14CD367D-4B5C-4C3C-86D5-F980DD6B16FE@hsd1.ma.comcast.net.]

On May 6, 2019, at 10:13 PM, Erik Demaine <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm a little confused what you mean. All text in Coauthor is fully justified (like default LaTeX). What are you seeing in that example that isn't as you expect? Also, which browser are you using? (Maybe what you're seeing is different from what I'm seeing.)

**Comment by edemaine** [comment]
The screenshot didn't come through. You'll need to use the Github interface (copy/paste works well) or send me a direct email. Thanks!

**Comment by tomhull0** [comment]
Ooops.  Here's the screen shot.  
<img width="1680" alt="Screen Shot 2019-05-06 at 10 28 50 PM" src="https://user-images.githubusercontent.com/18233285/57301041-145c8300-70a6-11e9-8f10-5e7308ad7ec0.png">

**Comment by edemaine** [comment]
Oh, I see now!  I was looking at it on a narrow screen so didn't see the effect.

I'm deploying a fix now.  Thanks for the bug report!
