### ISSUE TITLE
Can't fold an image with a child post

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#406]
Example: https://coauthor.csail.mit.edu/6.892-2019/m/P2FDbcoSJFALqhdPw

I can fold `3`, but when I try to fold `1` it immediately unfolds itself.

Feels related to #363?

**Comment by diomidov** [comment]
Actually the same thing happens when the child is a text post.

**Comment by edemaine** [comment]
Thanks for spotting this. Indeed, related to #363, but perhaps an older bug that only surfaced after #363 got fixed.
