### ISSUE TITLE
Let me set a message as initially-collapsed instead of deleting it

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#41]
When I delete a message, other users can't see it.  That may be appropriate for posts containing wrong claims/proofs.  For messages consisting of discussion, though, referring back to 'old' discussion may be useful even after having produced a 'finished product'.  I want to mark these messages as initially collapsed, to clean up the message thread without making them inaccessible to others.

I'm not entirely sure this is the feature I want to request; it's maybe more of a workflow question.  I'm hesitant to post a status-update message about a computer search I'm working on in a thread that until this point consists of claims and proofs only.  I want to get feedback about the search, but I don't want to clutter the thread with discussion, and on the third hand I don't want to delete any parts of our thought process.  (As an analogy, I often find searching through old e-mails useful to see what we were thinking.)

**Comment by edemaine** [comment]
Maybe #172 helps with this?  We could add a "default folded" option (maybe called "Unimportant?").

**Comment by jbosboom** [comment]
If an image message is initially-collapsed and not otherwise used in the page, the image won't be (or ought not to be) fetched until the message is expanded, making threads with many images load more quickly.  (Great for not pulling down multi-MB whiteboard photographs, for example.)

**Comment by edemaine** [comment]
I think more interesting than click-to-load would be scaling down large images into "thumbnails" of some size (perhaps depending on screen resolution...).  This requires background thumbnail generation, which is currently embodied by #39, though could perhaps use a separate issue.

**Comment by edemaine** [comment]
Now that we have an "Actions" drop-down, I think we should add a Hide/Show feature to set the default folded state for all users.  Is "Hide/Show" a good word for this?  Or perhaps "Fold/Unfold [for everyone]"?

**Comment by jbosboom** [comment]
I suggested "minimize" and "restore" (or "un-minimize"), by analogy with window managers.

**Comment by edemaine** [comment]
I went with Minimize and Unminimize (as Restore seems a little ambiguous, and this is parallel to Delete and Undelete).  I think I got all the autofolding logic correct (especially complicated by the image referencing logic).
