### ISSUE TITLE
Consider "auto" theme setting based on CSS prefers-color-scheme

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#411]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme exposes the OS's/window manager's light/dark theme preference.  You could use this for an "Auto" theme selection setting (and maybe make that the new default).

I don't know whether that should apply to the editor theme as well.

**Comment by edemaine** [comment]
Good idea. I think this should be the default when the user hasn't made a choice.

I'm not sure whether it needs to be a choosable option... do some people change their system theme e.g. depending on time of day? (If so, it should be choosable.)

We'd need to detect the setting via JavaScript, not CSS.  [Here's an article](https://www.freecodecamp.org/news/how-to-detect-a-users-preferred-color-scheme-in-javascript-ec8ee514f1ef/) about how to do so (even reactively) with `window.matchMedia`.

**Comment by edemaine** [comment]
I made "auto" a choosable theme; clicking cycles through auto, dark, light, auto, etc.

This isn't supported on Chrome 75 (current release), but it apparently will be supported on Chrome 76 (released in a few days?).

**Comment by edemaine** [comment]
Confirmed: Chrome 76 on Windows now automatically requests dark mode for me.  Yay!
