### ISSUE TITLE
Messages can be reparented to themselves

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#419]
See https://coauthor.csail.mit.edu/6.892-2019/m/5KdHefCJjEb5M3fJt .  (In retrospect, testing this on the production instance was a poor decision.  Move it back to under https://coauthor.csail.mit.edu/6.892-2019/m/w78PdDobviKipjoZp if you can/when you're done investigating.)

**Comment by edemaine** [comment]
@jbosboom Thanks for discovering this. There was a buggy edge case in the ancestor detection logic, now fixed. Phew!
