### ISSUE TITLE
Inline code in message titles

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#423]
![image](https://user-images.githubusercontent.com/22151995/61989976-ae78fb00-b005-11e9-9ce7-0d122cb10ead.png)
Inline `code` pops out too much when it's the title of a published (blue) message.

I think something like this would look better:
![image](https://user-images.githubusercontent.com/22151995/61990030-850c9f00-b006-11e9-88d0-8b7cda6b716d.png)

**Comment by diomidov** [comment]
Dark theme has the opposite problem:
![image](https://user-images.githubusercontent.com/22151995/61990429-a4a7c580-b00e-11e9-8896-f6990c699ba5.png)

**Comment by edemaine** [comment]
I found what I think is a reasonable compromise in all settings using an alpha component for the `<code>` background color.

Light mode:

![image](https://user-images.githubusercontent.com/2218736/61997139-3e9d5b80-b06b-11e9-9078-b42b43b0bf88.png)


Dark mode:

![image](https://user-images.githubusercontent.com/2218736/61997132-2d544f00-b06b-11e9-8be7-d427b56305fe.png)
