### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by tomhull0** [edemaine/coauthor#424]
Starting at about 10am-12pm (Eastern time) on 7/26/19, Coauthor stopped working well with Safari.  It works fine under Google Chrome and Firefox, but for me and 2 of my students (who use Safari) the posts no longer show in our group.  
<img width="1515" alt="Screen Shot 2019-07-27 at 11 08 15 AM" src="https://user-images.githubusercontent.com/18233285/61996138-eb251080-b05e-11e9-9c05-43aaef9cd756.png">

**Comment by diomidov** [comment]
Could it be related to theme auto-detection? 581a2746c689b3f755ca3dbf67e06859eb53b57d

**Comment by edemaine** [comment]
@tomhull0 Thanks for reporting.  Are you getting any messages in the Safari console?

@diomidov That may be a good guess, and may indeed be right, but it also looks like the theme *is* loading. (It would look really ugly if it didn't.)  But maybe some recent code tweak is raising an exception in Safari...

**Comment by tomhull0** [comment]
The Safari console says:

[Error] TypeError: o.addEventListener is not a function. (In 'o.addEventListener("change",i)', 'o.addEventListener' is undefined)
	theme.coffee (b47df9c06de7b77542f5f14b37760b8e564faa1b.js:209:262834)
	g (b47df9c06de7b77542f5f14b37760b8e564faa1b.js:3:1111)
	a (b47df9c06de7b77542f5f14b37760b8e564faa1b.js:5:4542)
	message.coffee (b47df9c06de7b77542f5f14b37760b8e564faa1b.js:209:201756)
	g (b47df9c06de7b77542f5f14b37760b8e564faa1b.js:3:1111)
	Global Code (b47df9c06de7b77542f5f14b37760b8e564faa1b.js:209:378438)

It says some other things too, but this is the one flagged as an Error.

**Comment by diomidov** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList

`MediaQueryList` doesn't inherit from `EventTarget` in Safari. We should use `addListener()` instead of `addEventListener()`.

**Comment by edemaine** [comment]
@tomhull0 Should be fixed now. Thanks for the console log which made it easy (for @diomidov) to debug without direct access to Safari.
