### ISSUE TITLE
[XSS] Javascript inside attachments

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#432]
1. Open a thread in two different windows (one is the attacker, the other is an unsuspecting victim).
2. Create an attachment post.
3. Replace the attachment with the following SVG:
```
<svg xmlns="http://www.w3.org/2000/svg">
    <script>
        alert(1);
    </script>
</svg>
```
4. Both windows display the alert!

The script is executed when you replace the file, but not when you load the thread or when you create a new attachment. I think this happens because you load the updated attachment in an `<iframe>` instead of `<img>`.

**Comment by jbosboom** [comment]
[MDN documents restrictions on SVG in `<img>`](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image#Restrictions), and I vaguely recall reading something more assertive that this is a required, cross-browser behavior.  So you really do need `<img>`.

**Comment by edemaine** [comment]
Thanks for finding this, @diomidov, and thanks for linking to the relevant constraints, @jbosboom.  I've [added](https://github.com/edemaine/coauthor/commit/51b68990da30fabdd61d1b93dae2973f2af01672) a [`sandbox` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) to the `<iframe>` which prevents the execution of scripts.  This does not prevent the loading of external resources [like `<img>` does](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image#Restrictions), but given that scripts will never be executable in the `<iframe>`, and the `<iframe>` isn't actually displayed, I can't see how this could be a problem (other than consuming bandwidth).  Let me know if I'm missing something.
