### ISSUE TITLE
Coauthor in subdirectory

### ISSUE THREAD

**Issue by manpen** [edemaine/coauthor#436]
In my installation `ROOT_URL` is set to `https://example.com/coauthorXXX/` and I use an Apache reverse proxy to pull coauthor into our regular domain. As far as I can tell, this works, with the exception of two minor bugs:

1.) The bootstrap theme is not loaded correctly. Replacing line 22 of `client/theme.coffee` with
```
    url = Meteor.absoluteUrl("/bootstrap/#{newTheme}.min.css")
    $('head').prepend """<link rel="stylesheet" href="#{url}" id="themeLink"/>"""
```
solves the problem.

2.) `client/layout.jade` line 90 contains `img(src="/favicon32.png")` and hence an absolute path.
As I do not have experience with jade, I cannot provide a fix for that.

**Comment by edemaine** [comment]
@manpen Thanks for testing this out -- nice that it mostly works as is!  I've pushed 2179619 which fixes all the absolute URLs I could find, including those you found.  Let me know if you spot any other issues.
