### ISSUE TITLE
Moving across groups

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#450]
- [ ] Moving a message to another group does not seem to move its children to the new group, leaving a bad parent relation
- [x] Moving a file message does not update the metadata for the file object, breaking the file subscription (unless the file message gets moved back).

**Comment by lvanbever** [comment]
Hi Erik,

Was just a victim of the 2nd part of this bug after moving threads across groups. Any quick fix I could do besides re-uploading the broken files?

Thanks!
Laurent

PS: Thank you for `coauthor` BTW, we're using it internally in our research group — and it's great!

**Comment by edemaine** [comment]
@lvanbever Yes, you can fix it via a manual Mongo operation. You should be able to get to the Mongo shell with a command like `mongo coauthor` on your server. Then do an operation like:
```js
db.fs.files.update({_id: ObjectId("123456789abcdef123456789")}, {$set: {"metadata.group": "newGroupName"}})
```

The ID is the one in the `file` attribute of the corresponding message. If you have Coauthor up, you can access that from the JavaScript console via `Messages.findOne('123456789abcdef123456789')` (where the message ID is the last part of the URL).

Let me know if you have any trouble. Sorry for the hassle! Time to fix the bug...

**Comment by edemaine** [comment]
@lvanbever Bug fixed. If you update to the latest version, and move the message to another group and back, it should fix the buggy file you have.

**Comment by lvanbever** [comment]
@edemaine Woot! Thanks for the lightning fast support on this! Will test that today.
