### ISSUE TITLE
Export messages, threads, groups to PDF

### ISSUE THREAD

**Issue by aureooms** [edemaine/coauthor#451]
## Feature Request
It would be nice to allow downloading all the content of all threads of a given group in a readable format in a single-click.

## Alternatives
Printing to PDF currently gives a nice offline document. It works for threads or the list of threads in a group. Unfortunately printing must be repeated for each thread if one wants the content for all threads.

## Use case
Workshops that used to be organized without coauthor handed a list of problems before the workshop. Now everything is online and it is your job to compile this list to have something to read on the plane.

## Options
It could be configured to ignore some information like list of people having read access.
Could also be configured to only print the root message of each thread.

**Comment by edemaine** [comment]
This seems to be roughly the same as #444, which I just pushed a first draft of.  Try the "download ZIP" button at the bottom of a group.

If you just want the root message of each thread, I'd recommend searching for `is:root` and printing that to PDF.

I'll close this in favor of #444.
