### ISSUE TITLE
Dependency contains vulnerabilities

### ISSUE THREAD

**Issue by sarahscheffler** [edemaine/coauthor#466]
[grunt-replace](https://github.com/outaTiME/grunt-replace) is a dependency of coauthor.  Down the dependency train, an outdated version of lodash contains three "prototype pollution" vulnerabilities, two of which are "high risk" ([1](https://nodesecurity.io/advisories/577), [2](https://nodesecurity.io/advisories/782), [3](https://nodesecurity.io/advisories/1065)).  Since the various parties seem not to be updating, somebody forked grunt-replace into [grunt-replace-regex](https://github.com/gbochenek/grunt-replace-regex) to get the updated dependency and resolve the vulnerability; coauthor should replace this dependency to address the vulnerability if it doesn't cause any functionality problems.

**Comment by edemaine** [comment]
Thanks for researching the replace replacement!  But note that these security vulnerabilities do not affect Coauthor, as grunt gets called only during build, not after deployment.
