### ISSUE TITLE
Image and PDF attachments no longer displayed

### ISSUE THREAD

**Issue by mwijaya** [edemaine/coauthor#476]
I noticed yesterday that the more recent attachments no longer show up. The older attachments showed up as usual, but I later realized that it's probably because they were cached. If I access my Coauthor group in incognito mode, none of the attachments shows up. I've tried using both Google Chrome (Ubuntu and Android) and Microsoft Edge.

When a PDF file is attached, a link will show up underneath the post. I've used that link to download PDF files before. When I click on the link now, I eventually arrive at a "504 Gateway Time-Out" page after a while.

**Comment by edemaine** [comment]
I'll need more information to help diagnose this, as Coauthor is continuing to work fine on my server.  What server are you using?  It sounds like an issue with the server.

**Comment by mwijaya** [comment]
I'm currently using the REU server that Tom Hull administers.

**Comment by edemaine** [comment]
Thanks! I'm actually the sys admin, so this is the right place to report the issue. I've confirmed it's a problem for me as well; I'll look into it now.

**Comment by NathanielKingsbury** [comment]
I'm also having this same problem, on the UConn REU server for the Fractals group (not sure who the administrator is). I've found further that I'm unable to upload PDF attachments (I click attach, and it looks as if it's in the process of attaching, but once it finishes the document never appears, either as a document or as a link).

**Comment by edemaine** [comment]
Should be fixed now. Let me know if you have any further issues.
