### ISSUE TITLE
Sidebar height is not recalculated on window resize when embedded in an iframe

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#484]
## What's wrong?
Sidebar height is not recalculated on window resize when embedded in an iframe.

This is especially annoying when embedded in Comingle.

## How to Reproduce
1. Open any thread in Comingle
2. Increase the window height
3. The sidebar now looks like this:

## Screenshots
![image](https://user-images.githubusercontent.com/22151995/93142981-01ec5380-f6b5-11ea-8930-17f2089cd201.png)

## Context
 - Device/OS:
 - Browser: Chrome
 - Coauthor server: coauthor.csail.mit.edu

**Comment by diomidov** [comment]
I think replacing
https://github.com/edemaine/coauthor/blob/bf43d8dc5517ca67051000ae8702fde569318bf8/client/message.coffee#L224-L225
with [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/Resize_Observer_API) could fix this

**Comment by edemaine** [comment]
iframes get window resize events no problem.  The issue was that we were resizing in one case (affix-top) but not the other case (affix).
