### ISSUE TITLE
Unclear reply buttons?

### ISSUE THREAD

**Issue by mehtank** [edemaine/coauthor#488]
## What's wrong?
(Similarly noted in https://github.com/edemaine/coauthor/issues/25#issuecomment-413453472)
I see a lot of entirely blank replies showing up -- there must be something confusing about the UI that causes someone to accidentally start a reply without intending to.

## How to Reproduce
1. Introduce several new users to Coauthor
2. Wait for a while and see blank replies everywhere

.

**Comment by edemaine** [comment]
I've tested the reproduction and it works! :-)

Do you have any suggestions on how to fix this?
1. One idea I had was to make the reply button require a second click to confirm, though that might be annoying.
2. A smaller fix would be to hide the reply buttons on a message being edited; I think some people expect the button to be the "done" button.
3. Another past idea is to make blank replies disappear automatically, but this is technically more difficult
4. Or blank replies could not even exist until they are nonempty, but this could potentially get in the way of collaboration. 

Meanwhile, a superuser can periodically search for `is:empty` and delete and superdelete all such messages. That's what I do currently.

**Comment by mehtank** [comment]
I think 2 would do the trick -- upon reflection it does make sense that users view the second "reply" button below the textbox as a "submit" button (like the "comment" button below the entry on gitlab).  Hiding the reply button below the entry would certainly help, or leaving the "stop editing" button where it is but moving the reply / attach buttons below some logical barrier.  Also, changing the button labels, e.g. "stop editing" -> "submit", "reply" -> "create new reply" or something similar might help?

**Comment by edemaine** [comment]
I've gone ahead and removed "reply" and "attach" buttons while editing. We'll see how the new user experience is. (Perhaps I should have kept "attach"? That's harder to do by accident, and *might* be useful. But this seemed more symmetric.)

I worry that the meaning of "Submit" might be a little unclear. One thing I'm trying to express (perhaps not very successfully) is that everyone can see your edits even when you're still editing.

**Comment by diomidov** [comment]
Can there be an option to re-enable Reply button for experienced users? It now takes 2 extra clicks to add a child post, and more importantly it adds an unnecessary entry to the history.

[relevant xkcd](https://xkcd.com/1172/)

**Comment by edemaine** [comment]
Based on my limited testing with the now-absent reply buttons, I don't think I've seen a decrease in empty messages.  Like @diomidov, I've also seen a few situations where I was annoyed by the lack of the reply button.  @mehtank have you noticed any effect (or was the timing off)? If the change isn't helping, maybe should put it back...

**Comment by mehtank** [comment]
Hm you're right, there are still empty messages popping up; I don't have a good count on whether it's more or less frequent than before the change.  Adding the reply buttons back is probably fine, but I think emphasizing the action as "Create new reply" in the button text will probably be helpful.

**Comment by edemaine** [comment]
While editing, reply button now becomes "Another Reply".  Maybe this will help?

**Comment by edemaine** [comment]
With the new reply dropdowns, I think we can close this. #541 might be a way to get rid of accidental blank replies too, at least in many cases.
