### ISSUE TITLE
Need to prevent dots from usernames

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#5]
Dots (`.`) cause bad things to happen in Mongo...

**Comment by edemaine** [comment]
Actually, we can support `.` in usernames with a bit of escaping.  This seems to only hit the `authors` structure, which is the only place we index by username.  Keep this in mind for the future though!

**Comment by jbosboom** [comment]
Do we need `.` in usernames?  If it's something we have to "keep in mind for the future", we're probably better off just disallowing it now.

**Comment by edemaine** [comment]
Jayson already made a username with a dot (`jaysonl@mit.edu`), which is why I ended up fixing this.  (I'm less sure how to restrict username selection. :-))
