### ISSUE TITLE
Duplicated characters around inline code blocks

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#527]
## What's wrong?
Sometimes characters around inline code blocks get duplicated.

Spotted in the wild [here](https://coauthor.csail.mit.edu/6.851-2017/m/nKws6yfPkGkt2a2Yb)

[Test post](https://coauthor.csail.mit.edu/coauthor-dev/m/JNNJYd8gzxmrAyTzw)

## How to Reproduce
1. Create a new post containing
```
`foo`, `bar`
`foo`, `bar`
`foo`, `bar`
```
2. The first comma, the first line break(!), the second and third `b`s, and the third `f` get duplicated!

## Screenshots
![image](https://user-images.githubusercontent.com/22151995/108585339-fd882e80-7315-11eb-8150-5a032cdb32e1.png)

## Context
 - Device/OS: GNU/Linux
 - Browser: Firefox, Chromium
 - Coauthor server: coauthor.csail.mit.edu

**Comment by diomidov** [comment]
I think the solution to both issues is to replace the last capturing group `([^`]|$)` with a negative lookahead `(?!`)`.

(well, the real solution is to stop writing unmaintainable regex parsers, but you already know this...)

**Comment by edemaine** [comment]
Thanks for finding and fixing this!
