### ISSUE TITLE
Math mode in comments

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#535]
## What's wrong?
If a comment ends in `$...$-->`, nothing after it is rendered. The issue is that `postprocessKaTeX` inserts a `<span class="nobr">` around math mode **and punctuation directly after it**. In this case, punctuation is `--`. So you get
```
<!--
  <span class="nobr">
    <span class="katex">...</span>
    --
  </span>
>
```

## How to Reproduce
https://coauthor.csail.mit.edu/coauthor-dev/m/P2FDbcoSJFALqhdPw

## Screenshots
![image](https://user-images.githubusercontent.com/22151995/111712250-9f227300-8823-11eb-9753-08d72c5758f5.png)

## Context
 - Device/OS: GNU/Linux
 - Browser: Firefox
 - Coauthor server: coauthor.csail.mit.edu

**Comment by edemaine** [comment]
Should be fixed with #465.
