### ISSUE TITLE
Dark mode scrollbars

### ISSUE THREAD

**Issue by diomidov** [edemaine/coauthor#548]
The dark mode scrollbars are ugly and ***not dark***.

Chrome:
![image](https://user-images.githubusercontent.com/22151995/114979827-896f9000-9e59-11eb-88b9-7d7cbf61e576.png)

Firefox:
![image](https://user-images.githubusercontent.com/22151995/114979872-97bdac00-9e59-11eb-9572-d9dfa4b29a88.png)

All the cool kids are using [`scrollbar-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) now! (okay, I've only seen it used by youtube so far, but still...)

**Comment by edemaine** [comment]
I guess by "cool kids" you mean Firefox: Chrome doesn't support `scrollbar-color`. 🙁 I guess [this tutorial](https://www.digitalocean.com/community/tutorials/css-scrollbars) will do it.
