### ISSUE TITLE
Rendering glitch on group page

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#58]
![visualglitch](https://cloud.githubusercontent.com/assets/7757340/13974286/df8af3bc-f080-11e5-98cd-97c2b8c07fc5.png)

The whole row should highlight, but the single-line cells are not completely highlighted.

(Also, I could live with a more compressed date format: "Wed Dec 16 2015 at 16:44" would be entirely acceptable and less likely to wrap.)

**Comment by edemaine** [comment]
OK, it highlights now.  I couldn't get the <a> tag to grow to fill the table cell, though, so you can still only click on the lines that contain text (as in the highlighted region shown above).  This seems to be a well-known challenge called "100% height columns", with no nice solution at least with real tables. :-(
