### ISSUE TITLE
no routes definition found

### ISSUE THREAD

**Issue by h0m3brew** [edemaine/coauthor#601]
## What's wrong?
This issue is still existing
## How to Reproduce
Steps to reproduce the behavior, e.g., link to where to see the behavior:

## Screenshots
If applicable, paste in screenshots of the bug.

## Context
 - Device/OS:
 - Browser: Chrome/Firefox/Safari/Edge/..., ideally with version
 - Coauthor server:

**Comment by edemaine** [comment]
Usually this happens when there's a crash on the client side. Can you fill out the bug report with the console error messages?
