### ISSUE TITLE
Missing dependency @fortawesome/fontawesome-svg-core

### ISSUE THREAD

**Issue by cgevans** [edemaine/coauthor#611]
## What's wrong?
On a clean installation (nvm-handled node 14, npm-installed meteor, on Debian 11), `@fortawesome/fontawesome-svg-core` is noted as not resolving:

```
Unable to resolve some modules:              
                                                                                                                                            
  "@fortawesome/fontawesome-svg-core" in /home/coauthor/coauthor/node_modules/@fortawesome/react-fontawesome/index.js (web.browser.legacy)
                                               
If you notice problems related to these missing modules, consider running:
                                                                                                                                            
  meteor npm install --save @fortawesome/fontawesome-svg-core    
```

Coauthor runs, but in Firefox and Chrome (latest versions, on Arch Linux), nothing on the page loads.  Installing the dependency as recommended fixes the problem.

`@fortawesome/fontawesome-svg-core` should likely be added to the dependencies in package.json.

**Comment by edemaine** [comment]
Looks like this was a peer dependency issue, specific to NPM 6 (not 5 or 7). Thanks for reporting!
