### ISSUE TITLE
Unable to open a group using Safari

### ISSUE THREAD

**Issue by lbrndnr** [edemaine/coauthor#619]
## What's wrong?
When trying to open a group (shown right underneath "Groups you're a member of"), the website gets stuck. A spinning progress indicator is shown, but nothing else happens.

## How to Reproduce
Steps to reproduce the behavior, e.g., link to where to see the behavior:
1. Load coauthor
2. Click on any group in the section "Groups you're a member of"

## Context
 - Device/OS: MacBook with macOS 13.4.1
 - Browser: Safari 16.5.2

**Comment by edemaine** [comment]
We could not reproduce this on two test devices here running the same version of Safari.

Are you using the CSAIL Coauthor server, or another one? It could be you're running an older version of Coauthor, in which case you'll have to request your server admins to upgrade.

**Comment by lbrndnr** [comment]
Okay thanks for checking! I will verify the server version then
