### ISSUE TITLE
Allowing multiple cursors for collaborators to edit reply concurrently

### ISSUE THREAD

**Issue by nicolelu** [edemaine/coauthor#626]
Right now, it seems like the reply box allows all collaborators to see the changes being made, but practically only lets one person type at a time since all collaborators control the same cursor and end up messing up each other's typing. It's a nice-to-have, but being able to have fully separate cursors to enable multiple people typing concurrently on the same message without interfering with each other (like google docs) would be amazing! Even if you had to add restrictions (like locking a chunk of text around each author's cursor), this would still be helpful.

**Comment by edemaine** [comment]
Hmm, I don't understand. It should already work that way: multiple people can edit at multiple places in a message, without conflict. Only if you're editing at exactly the same spot would there be an issue.

Admittedly you can't see the other users' cursors. That'd be really nice, but isn't possible without a significant rewrite.

If you're not getting this behavior, I need to know more about what browsers and devices you're using.

**Comment by nicolelu** [comment]
Ah okay - probably user error then. We'll try it again in class today to see if there was something we were doing wrong. Thanks!
