### ISSUE TITLE
Verification emails not being received

### ISSUE THREAD

**Issue by ThomasHull1** [edemaine/coauthor#643]
## What's wrong?
Multiple new users of Coauthor are reporting never receiving a verification email when creating a new account in Coauthor.  We are using the https://reu-coauthor.csail.mit.edu server.

## How to Reproduce
Well, I reproduced the error myself by creating a new account with a spare Gmail address that I have.  I also did not receive a verification email.

## Screenshots
Not applicable.

## Context
 - Device/OS: Mac, OS 14.5
 - Browser: I reproduced the error using Chrome Version 125.0.6422.142
 - Coauthor server: https://reu-coauthor.csail.mit.edu

**Comment by edemaine** [comment]
Thanks for the report! Can you test again? (You can request the verification email to be sent again under Settings.)

I tweaked some settings that should enable delivery from reu-coauthor to Gmail (and added instructions to `INSTALL.md` for future reference).

**Comment by ThomasHull1** [comment]
Yes, that worked.  Thanks!

--- Tom
