### ISSUE TITLE
Embedding PDFs

### ISSUE THREAD

**Issue by qqliu** [edemaine/coauthor#65]
I think you can embed a PDF using <object>:

```html
<object data="/gridfs/fs/id/90d307bd816692fef8048803" type="application/pdf" width="100%" height="100%"> Woops, your browser
does not support PDFs.
</object>
```

Also can be used for videos/audio/any other multimedia file.

**Comment by jbosboom** [comment]
GitHub Enterprise now renders PDFs client-side; see, e.g., https://github.mit.edu/quanquan/6.890-lecture07/blob/master/L07_images.pdf .  Looking at the source, they seem to be using pdf.js, but that's all I know.

This does require actually fetching the PDFs, though, so having some server-side thumbnails to start with (#39) would still be useful.
