### ISSUE TITLE
Collapse messages in Live Feed view

### ISSUE THREAD

**Issue by jaysonl** [edemaine/coauthor#67]
I don't see the normal minus sign to collapse messages in the Live Feed view. I'd assume it's also missing from the Catch Up on Recent Messages.

**Comment by edemaine** [comment]
My thought was that it doesn't make a lot of sense to collapse messages that don't have children listed.  I take it you disagree?  I don't think it would be too hard to add...

**Comment by edemaine** [comment]
This was fixed some time ago.
