### ISSUE TITLE
Live Feed and Recent Messages names

### ISSUE THREAD

**Issue by jaysonl** [edemaine/coauthor#68]
My intuition is that live feed should be time based and recent messages should be message based. What do other people think? Are there other names that are clearer?

**Comment by edemaine** [comment]
"Live Feed" seems like a natural name for what it does (show the last n messages).  How about "Catchup Since..." for the other?  (The intent is that it lets you catch up on all messages since a particular date.)  I've also added tooltips to make what they do especially clear.
