### ISSUE TITLE
Transient permission problem with file/image downloads

### ISSUE THREAD

**Issue by tomhull0** [edemaine/coauthor#69]
Hi!  I'm not seeing jpg files in Coauthor, most recently in the Flattening Polyhedra with Slits thread.  (I get a broken graphic icon.)  I'm using a MacBook Pro running OS10.11.4, and I tried it in Chrome, Firefow, and SeaMonkey. 

But the jpg files in Forcing Sets via Graph Theory show up just fine for me!  Eeep?

--- Tom

**Comment by edemaine** [comment]
I assume all images aren't loading. Are you using a new machine, or have you not used Coauthor for a while? I'm not sure what causes this, but I (and others) have seen it, and it seems to go away after a while...

**Comment by tomhull0** [comment]
Well, before jpegs were visible on some Coauthor pages and not others.  But now they all seem to work fine.  Not using a new machine, but it's true I hadn't looked at Coauthor in 5 days or so.  Anyway, it's working now.
