### ISSUE TITLE
Send 304 Not Modified for uploaded files when applicable

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#78]
Coauthor's own resources (e.g., 185378fb692339231a2abfe954ab98639c0a14ec.js?meteor_js_resource=true, ace.js) are served with `Etag` and `Last-Modified`; my browser (Firefox 45.0.2) properly sends `If-Modified-Since` and `If-None-Match` and the server properly responds with `304 Not Modified`.

Uploaded files are served with `Last-Modified` but not `Etag`.  My browser sends `If-Modified-Since` with a date, and the server responds with `200 OK` featuring `Last-Modified` with that exact same date.  The [specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25) says the server should be sending `304 Not Modified` here.  (It even calls out in a note: "To get best results when sending an If-Modified-Since header field for cache validation, clients are advised to use the exact date string received in a previous Last-Modified header field whenever possible.")

I'm not sure if this is a problem with Coauthor or the configuration of the server hosting it, but it's annoying.

**Comment by edemaine** [comment]
Thanks for the report.  This is an issue with the [meteor-file-collection](https://github.com/vsivsi/meteor-file-collection) which maintains uploaded files.  Reported upsteam as https://github.com/vsivsi/meteor-file-collection/issues/108

**Comment by edemaine** [comment]
@jbosboom Could you test to make sure the new server behaves as you desire?

**Comment by jbosboom** [comment]
@edemaine It works.
