### ISSUE TITLE
Upgrade MongoDB / Meteor

### ISSUE THREAD

**Issue by edemaine** [edemaine/coauthor#83]
- [x] Meteor 1.4: https://guide.meteor.com/1.4-migration.html
- [ ] MongoDB 2.6 -> 3.0 -> 3.2:
  * https://guide.meteor.com/1.4-migration.html#update-to-mongo-3_2
  * https://docs.mongodb.com/manual/release-notes/3.0-upgrade/
  * https://docs.mongodb.com/manual/release-notes/3.2-upgrade/
- [x] mup should also be upgraded, to mupx: https://github.com/kadirahq/meteor-up

**Comment by edemaine** [comment]
I've done everything except update the MongoDB format to wiredTiger.  I'll turn that into a new issue.

**Comment by aureooms** [comment]
(the new issue in question is #88)
