### ISSUE TITLE
Meta-issue: import issues from brainstorming session

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#9]
In one of the 6.890 sessions we brainstormed desiderata for Coauthor in Google Docs.  They should be imported into this issue tracker.

**Comment by edemaine** [comment]
I've actually had several such brainstorms, and all notes are collected in [one Google Doc](https://docs.google.com/document/d/111dU7oXZD5DT4jOkTDkXTcPrauJ25M4en-MwP5Z5sRQ/edit).  Feel free to request access to view/edit.  I wouldn't post those issues blindly, but with some filtering, yes.

Same goes for migrating stuff out of TODO.txt currently in the repository.

**Comment by edemaine** [comment]
Most existing issues seem to have already been raised here (in some cases, recently).
