### ISSUE TITLE
Link directly to attached file yields the file, but also "message “” does not exist"

### ISSUE THREAD

**Issue by jbosboom** [edemaine/coauthor#92]
I edited a message to contain a link directly to an attached file.  Clicking on that link does result in retrieving the file (Firefox asks me if I want to open or save it, as usual), but also sends me to a page saying "The message “” does not exist or you do not have permission to access it."  I think I should remain on the previous page, if possible.

**Comment by edemaine** [comment]
I've been unable to reproduce this.  What URL is listed in the browser when this happens?  Perhaps it's a side-effect of some Firefox plugin/preference you have which does the open/save ask for PDF files?  I just tried on https://coauthor.csail.mit.edu/6.890/m/GregWnZ3Dm6hWMLXx in Firefox, and I get what seems to be a built-in Firefox PDF plugin (no other plugins are enabled) displaying the attachment.

**Comment by jbosboom** [comment]
I'm not seeing the "does not exist or you do not have permission" page anymore, though there's still a little weirdness:

If I open https://coauthor.csail.mit.edu/6.890/m/GregWnZ3Dm6hWMLXx and click the "can be parsed" link in that post, in addition to seeing Firefox's save-or-open-the-download dialog, the orange "Users" button in the upper-right disappears and the right-facing-arrow "Focus" button appears in that post's header.  The browser's URL does not change.

If I navigate to that thread's top level message from the group's list of threads, I can get the same buttons-appear-and-disappear behavior when clicking that link, with the "Focus" button appearing on the top-level message.

**Comment by edemaine** [comment]
I guess Meteor is updating the display after the URL changes but before the browser actually goes to the link and determines that it's a file...  Not sure how to fix this.
